### ISSUE TITLE
No License Specified

### ISSUE THREAD

**Issue by JayesonLS** [carlk3/no-OS-FatFS-SD-SPI-RPi-Pico#13]
Nice work on the library Carl. 

It doesn't look like you have specified a license for your modifications/additions. Did you intend for your work to be Apache 2.0, public domain or something else?

**Comment by carlk3** [comment]
See https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/pull/20#issue-1077598827
