### ISSUE TITLE
Disable GP25 LED

### ISSUE THREAD

**Issue by ikjordan** [carlk3/no-OS-FatFS-SD-SPI-RPi-Pico#15]
The code in `spi.h` allows for the use of the Pico LED (on GP25) to be configured, but it is hard coded to flash. A simple change
`#ifndef NO_PICO_LED`  
`#define USE_LED 1`  
`#endif`  
Allows the LED to be disabled via CMake for a project that uses no-OS-FatFS-SD-SPI-RPi-Pico as a submodule, whilst maintaining backwards compatibility. 

I can submit a pull request if you'd like?

**Comment by carlk3** [comment]
Ah, yes, that looks like a good change. 

Yes, please submit a pull request.

**Comment by carlk3** [comment]
This has gotten more interesting with the advent of the Pico W. See #74. The W uses GPIO 25 for SPI communication to the CYW43439. I'm going to change the default to disabling the LED.
