### ISSUE TITLE
DMA IRQs should be handled in RAM

### ISSUE THREAD

**Issue by fruit-bat** [carlk3/no-OS-FatFS-SD-SPI-RPi-Pico#18]
I have some issues with the PicoDVI library; if the IRQ handlers execute from flash memory rather than RAM. 
The 2 routines in question are defined in spi.h :

1. void spi_irq_handler(spi_t *pSPI);
2. bool spi_transfer(spi_t *pSPI, const uint8_t *tx, uint8_t *rx, size_t length);

Please could they be pinned to RAM:

1. void __not_in_flash_func(spi_irq_handler)(spi_t *pSPI);
2. bool __not_in_flash_func(spi_transfer)(spi_t *pSPI, const uint8_t *tx, uint8_t *rx, size_t length);

I have included the git diff below if it is clearer.

(I can fork and pull request if you prefer)

Many thanks in advance.

diff --git a/FatFs_SPI/sd_driver/spi.h b/FatFs_SPI/sd_driver/spi.h
index fc13226..749506c 100644
--- a/FatFs_SPI/sd_driver/spi.h
+++ b/FatFs_SPI/sd_driver/spi.h
@@ -47,9 +47,9 @@ extern "C" {
 #endif
 
     // SPI DMA interrupts
-    void spi_irq_handler(spi_t *pSPI);
+    void __not_in_flash_func(spi_irq_handler)(spi_t *pSPI);^M
 
-    bool spi_transfer(spi_t *pSPI, const uint8_t *tx, uint8_t *rx, size_t length);
+    bool __not_in_flash_func(spi_transfer)(spi_t *pSPI, const uint8_t *tx, uint8_t *rx, size_t length);^M
     bool my_spi_init(spi_t *pSPI);
 
 #ifdef __cplusplus

**Comment by carlk3** [comment]
That looks fine to me. Yes, please create a Pull Request.
