### ISSUE TITLE
FatFs_SPI version ff15

### ISSUE THREAD

**Issue by icboz** [carlk3/no-OS-FatFS-SD-SPI-RPi-Pico#39]
Hello,

First of all, thank you for this library.

Version ff14a of FatFs_SPI does not support writing floats with f_printf. In ff15 version there is a FF_PRINT_FLOAT define and it lets you use f_printf with floats. I solved it by copying the ff15 files inside this library. 

I wanted to open a pull request, but I do not fully know what all ffconf.h options should be.

**Comment by carlk3** [comment]
Please review Pull Request #40.
