### ISSUE TITLE
SDIO example?

### ISSUE THREAD

**Issue by piverson110** [carlk3/no-OS-FatFS-SD-SPI-RPi-Pico#62]
As far as I can see, there is no example of SDIO being implemented in this library. I see "Customising the hardware configuration" and some relevant structures, but the documentation and examples are focused on SPI. I know that the specific configuration will depend on how the sd card is wired, but does anyone have a working SDIO example to share?

**Comment by carlk3** [comment]
Are you looking at the [sdio ](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/tree/sdio) branch?

[dynamic_config](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/tree/sdio/examples/dynamic_config) uses SDIO. There are also a few examples in the [PlatformIO](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/tree/sdio/examples/PlatformIO) subdirectory that use SDIO.

**Comment by piverson110** [comment]
Cheers, I'll check those out.

**Comment by carlk3** [comment]
Also, the [command_line](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/tree/sdio/examples/command_line) example shows SDIO in a static configuration (with [hw_config.c](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/blob/sdio/examples/command_line/hw_config.c)).

**Comment by piverson110** [comment]
Thanks! I got confused by the various options, but now I've got it working easily on a self-designed PCB.
