### ISSUE TITLE
static_assert().......

### ISSUE THREAD

**Issue by Freyte** [carlk3/no-OS-FatFS-SD-SPI-RPi-Pico#64]
is it a version for Micro Sd card Adapter in C ?

**Comment by carlk3** [comment]
Yes. One C example: [simple](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/tree/sdio/examples/simple)

**Comment by Freyte** [comment]
Really thank you, i tried to work with but I am having a problem to made the .uf2 of the simple. Did you also have this kind of problems or similar? 
![Capture](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/assets/127773641/4c19970e-7d09-4dda-8567-94e14cd4e347)

**Comment by carlk3** [comment]
What `gcc` version are you using? I'm using

`arm-none-eabi-gcc.exe (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)`

I don't know how long `static_assert` has been around. Anyway, it is just a compile time assertion.. You can just comment it out.

**Comment by Freyte** [comment]
I have a version gcc (Debian 10.2.1-6) 10.2.1 Copyright (c) 2020 Free Software Foundation, Inc.
I took your advice to comment it out and works. Thank you so much
