### ISSUE TITLE
megadrive request (excuse)

### ISSUE THREAD

**Issue by turuwhiska** [carlk3/no-OS-FatFS-SD-SPI-RPi-Pico#67]
Hello, this is off topic, but I have no other way to contact you.
I saw your Sega Megadrive Flash Cart project, I would like to see the sources, or basically know how the OE and CS lines work in the FPGA
My idea is to use Mister's core (sega cd) and see if I can add these physical lines. what do you think?

**Comment by carlk3** [comment]
I don't know anything about Sega Megadrive. You must be thinking of someone else.
