### ISSUE TITLE
Help compiling library for GCC (C++)

### ISSUE THREAD

**Issue by MisterSandman7** [carlk3/no-OS-FatFS-SD-SPI-RPi-Pico#7]
The library compiles fine for .c files, but when switching the main to .cpp and updating the Cmake configuration 8 errors pop up from the sd_driver folder, all saying `expected ',' or '...' before 'this'`.
These errors appear in the files `sd_card.h` between lines 64 to 70 and in 'spi.h` between lines 46 to 49.

I'm not sure how to solve this issue (I tried to extern "C", but that didn't do anything).

Any help would be appreciated.
Here's both the log and error files if they can be of any help.
[CMakeError.log](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/files/6949868/CMakeError.log)
[CMakeOutput.log](https://github.com/carlk3/no-OS-FatFS-SD-SPI-RPi-Pico/files/6949871/CMakeOutput.log)

**Comment by carlk3** [comment]
I shouldn't have used the identifier "this", since that is a keyword in C++. For now, I think you could just do a global search and replace of "this" with "me", or "inst", or whatever. But I will correct this.

**Comment by MisterSandman7** [comment]
Thought the same, `this` is a C++ keyword. I'll try to patch up and see if it compiles.

**Comment by carlk3** [comment]
I have committed a new version that works with a C++ main.
